# CaptureEngine ABI 63, source c13145ecefabdb18a48b245b3861fd5bdaeb8551.
set(CAPTURE_ENGINE_BUNDLE_DIR "" CACHE PATH "Directory containing the pinned CaptureEngine hooks and LICENSE")
option(SUNSHINE_BUNDLE_DIRECT_CAPTURE "Bundle the pinned direct game capture hooks" ON)
if(SUNSHINE_BUNDLE_DIRECT_CAPTURE AND NOT CAPTURE_ENGINE_BUNDLE_DIR)
    set(_ce_archive "${CMAKE_BINARY_DIR}/capture-engine-abi63-20260928.zip")
    set(_ce_sha256 "069083bf55546aeef5cb44b0ec4735c79db290316387360392249bdf1a772403")
    if(EXISTS "${_ce_archive}")
        file(SHA256 "${_ce_archive}" _ce_cached_hash)
    endif()
    if(NOT _ce_cached_hash STREQUAL _ce_sha256)
        file(DOWNLOAD
            "https://github.com/Cynary/capture-engine/releases/download/vibepollo-abi63-20260928/capture-engine-abi63.zip"
            "${_ce_archive}"
            EXPECTED_HASH "SHA256=${_ce_sha256}"
            TLS_VERIFY ON TIMEOUT 120)
    endif()
    set(CAPTURE_ENGINE_BUNDLE_DIR "${CMAKE_BINARY_DIR}/capture-engine-abi63-20260928")
    file(ARCHIVE_EXTRACT INPUT "${_ce_archive}" DESTINATION "${CAPTURE_ENGINE_BUNDLE_DIR}")
endif()
if(CAPTURE_ENGINE_BUNDLE_DIR)
    set(_ce_names capture_hook_x64.dll capture_hook_x86.dll)
    set(_ce_hashes c17758ea8940d8e42445521f25316aeaa0fcbe7492c89aad4dc6277c2f8ec5bb 9824cabe94883cb9c0fb8cd07dc7360d4be7a882e557e8cc73a3426b179741ea)
    foreach(_index RANGE 0 1)
        list(GET _ce_names ${_index} _name)
        list(GET _ce_hashes ${_index} _expected)
        set(_file "${CAPTURE_ENGINE_BUNDLE_DIR}/${_name}")
        if(NOT EXISTS "${_file}")
            message(FATAL_ERROR "Missing CaptureEngine hook: ${_file}")
        endif()
        file(SHA256 "${_file}" _actual)
        if(NOT _actual STREQUAL _expected)
            message(FATAL_ERROR "CaptureEngine hook does not match the pinned ABI 63 build: ${_name}")
        endif()
        install(FILES "${_file}" DESTINATION tools/capture-engine COMPONENT application)
    endforeach()
    if(NOT EXISTS "${CAPTURE_ENGINE_BUNDLE_DIR}/LICENSE")
        message(FATAL_ERROR "CaptureEngine bundle must include LICENSE")
    endif()
    install(FILES "${CAPTURE_ENGINE_BUNDLE_DIR}/LICENSE" DESTINATION tools/capture-engine COMPONENT application)
endif()
